/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as HarvestsIdRouteImport } from './routes/harvests/$id'
import { Route as FarmerWelcomeRouteImport } from './routes/farmer/welcome'
import { Route as FarmerStockRouteImport } from './routes/farmer/stock'
import { Route as FarmerProfileRouteImport } from './routes/farmer/profile'
import { Route as FarmerOrdersRouteImport } from './routes/farmer/orders'
import { Route as FarmerOnboardingRouteImport } from './routes/farmer/onboarding'
import { Route as FarmerDashboardRouteImport } from './routes/farmer/dashboard'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer/analytics'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth/unauthorized'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuctionsStoryRouteImport } from './routes/auctions/story'
import { Route as AuctionsIdRouteImport } from './routes/auctions/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as FarmerAuctionsIndexRouteImport } from './routes/farmer/auctions/index'
import { Route as OrdersIdTrackingRouteImport } from './routes/orders/$id/tracking'
import { Route as HarvestsIdQualityRouteImport } from './routes/harvests/$id/quality'
import { Route as FarmerProductsIdRouteImport } from './routes/farmer/products/$id'
import { Route as FarmerHarvestsNewRouteImport } from './routes/farmer/harvests/new'
import { Route as FarmerHarvestsAnalyzeRouteImport } from './routes/farmer/harvests/analyze'
import { Route as FarmerAuctionsNewRouteImport } from './routes/farmer/auctions/new'
import { Route as FarmerAuctionsIdBiddersRouteImport } from './routes/farmer/auctions/$id.bidders'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const HarvestsIdRoute = HarvestsIdRouteImport.update({
  id: '/harvests/$id',
  path: '/harvests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerWelcomeRoute = FarmerWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerStockRoute = FarmerStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersRoute = FarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOnboardingRoute = FarmerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsStoryRoute = AuctionsStoryRouteImport.update({
  id: '/auctions/story',
  path: '/auctions/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAuctionsIndexRoute = FarmerAuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => FarmerRoute,
} as any)
const OrdersIdTrackingRoute = OrdersIdTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => OrdersIdRoute,
} as any)
const HarvestsIdQualityRoute = HarvestsIdQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => HarvestsIdRoute,
} as any)
const FarmerProductsIdRoute = FarmerProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHarvestsNewRoute = FarmerHarvestsNewRouteImport.update({
  id: '/harvests/new',
  path: '/harvests/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHarvestsAnalyzeRoute = FarmerHarvestsAnalyzeRouteImport.update({
  id: '/harvests/analyze',
  path: '/harvests/analyze',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAuctionsNewRoute = FarmerAuctionsNewRouteImport.update({
  id: '/auctions/new',
  path: '/auctions/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAuctionsIdBiddersRoute = FarmerAuctionsIdBiddersRouteImport.update({
  id: '/auctions/$id/bidders',
  path: '/auctions/$id/bidders',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/farmer/auctions/': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions': typeof AuctionsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/farmer/auctions': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/farmer/auctions/': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/farmer'
    | '/marketplace'
    | '/notifications'
    | '/orders'
    | '/admin/roles'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/login'
    | '/auth/register'
    | '/auth/unauthorized'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/orders/$id'
    | '/auctions/'
    | '/orders/'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/orders/$id/tracking'
    | '/farmer/auctions/'
    | '/farmer/auctions/$id/bidders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/farmer'
    | '/marketplace'
    | '/notifications'
    | '/admin/roles'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/login'
    | '/auth/register'
    | '/auth/unauthorized'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/orders/$id'
    | '/auctions'
    | '/orders'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/orders/$id/tracking'
    | '/farmer/auctions'
    | '/farmer/auctions/$id/bidders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/farmer'
    | '/marketplace'
    | '/notifications'
    | '/orders'
    | '/admin/roles'
    | '/admin/users'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/login'
    | '/auth/register'
    | '/auth/unauthorized'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/orders/$id'
    | '/auctions/'
    | '/orders/'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/orders/$id/tracking'
    | '/farmer/auctions/'
    | '/farmer/auctions/$id/bidders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  AuctionsStoryRoute: typeof AuctionsStoryRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  HarvestsIdRoute: typeof HarvestsIdRouteWithChildren
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/harvests/$id': {
      id: '/harvests/$id'
      path: '/harvests/$id'
      fullPath: '/harvests/$id'
      preLoaderRoute: typeof HarvestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/welcome': {
      id: '/farmer/welcome'
      path: '/welcome'
      fullPath: '/farmer/welcome'
      preLoaderRoute: typeof FarmerWelcomeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/stock': {
      id: '/farmer/stock'
      path: '/stock'
      fullPath: '/farmer/stock'
      preLoaderRoute: typeof FarmerStockRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders': {
      id: '/farmer/orders'
      path: '/orders'
      fullPath: '/farmer/orders'
      preLoaderRoute: typeof FarmerOrdersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/onboarding': {
      id: '/farmer/onboarding'
      path: '/onboarding'
      fullPath: '/farmer/onboarding'
      preLoaderRoute: typeof FarmerOnboardingRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/story': {
      id: '/auctions/story'
      path: '/auctions/story'
      fullPath: '/auctions/story'
      preLoaderRoute: typeof AuctionsStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/auctions/': {
      id: '/farmer/auctions/'
      path: '/auctions'
      fullPath: '/farmer/auctions/'
      preLoaderRoute: typeof FarmerAuctionsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/orders/$id/tracking': {
      id: '/orders/$id/tracking'
      path: '/tracking'
      fullPath: '/orders/$id/tracking'
      preLoaderRoute: typeof OrdersIdTrackingRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/harvests/$id/quality': {
      id: '/harvests/$id/quality'
      path: '/quality'
      fullPath: '/harvests/$id/quality'
      preLoaderRoute: typeof HarvestsIdQualityRouteImport
      parentRoute: typeof HarvestsIdRoute
    }
    '/farmer/products/$id': {
      id: '/farmer/products/$id'
      path: '/products/$id'
      fullPath: '/farmer/products/$id'
      preLoaderRoute: typeof FarmerProductsIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/harvests/new': {
      id: '/farmer/harvests/new'
      path: '/harvests/new'
      fullPath: '/farmer/harvests/new'
      preLoaderRoute: typeof FarmerHarvestsNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/harvests/analyze': {
      id: '/farmer/harvests/analyze'
      path: '/harvests/analyze'
      fullPath: '/farmer/harvests/analyze'
      preLoaderRoute: typeof FarmerHarvestsAnalyzeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/auctions/new': {
      id: '/farmer/auctions/new'
      path: '/auctions/new'
      fullPath: '/farmer/auctions/new'
      preLoaderRoute: typeof FarmerAuctionsNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/auctions/$id/bidders': {
      id: '/farmer/auctions/$id/bidders'
      path: '/auctions/$id/bidders'
      fullPath: '/farmer/auctions/$id/bidders'
      preLoaderRoute: typeof FarmerAuctionsIdBiddersRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerOnboardingRoute: typeof FarmerOnboardingRoute
  FarmerOrdersRoute: typeof FarmerOrdersRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerStockRoute: typeof FarmerStockRoute
  FarmerWelcomeRoute: typeof FarmerWelcomeRoute
  FarmerAuctionsNewRoute: typeof FarmerAuctionsNewRoute
  FarmerHarvestsAnalyzeRoute: typeof FarmerHarvestsAnalyzeRoute
  FarmerHarvestsNewRoute: typeof FarmerHarvestsNewRoute
  FarmerProductsIdRoute: typeof FarmerProductsIdRoute
  FarmerAuctionsIndexRoute: typeof FarmerAuctionsIndexRoute
  FarmerAuctionsIdBiddersRoute: typeof FarmerAuctionsIdBiddersRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerOnboardingRoute: FarmerOnboardingRoute,
  FarmerOrdersRoute: FarmerOrdersRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerStockRoute: FarmerStockRoute,
  FarmerWelcomeRoute: FarmerWelcomeRoute,
  FarmerAuctionsNewRoute: FarmerAuctionsNewRoute,
  FarmerHarvestsAnalyzeRoute: FarmerHarvestsAnalyzeRoute,
  FarmerHarvestsNewRoute: FarmerHarvestsNewRoute,
  FarmerProductsIdRoute: FarmerProductsIdRoute,
  FarmerAuctionsIndexRoute: FarmerAuctionsIndexRoute,
  FarmerAuctionsIdBiddersRoute: FarmerAuctionsIdBiddersRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface OrdersIdRouteChildren {
  OrdersIdTrackingRoute: typeof OrdersIdTrackingRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdTrackingRoute: OrdersIdTrackingRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface HarvestsIdRouteChildren {
  HarvestsIdQualityRoute: typeof HarvestsIdQualityRoute
}

const HarvestsIdRouteChildren: HarvestsIdRouteChildren = {
  HarvestsIdQualityRoute: HarvestsIdQualityRoute,
}

const HarvestsIdRouteWithChildren = HarvestsIdRoute._addFileChildren(
  HarvestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FarmerRoute: FarmerRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  AuctionsStoryRoute: AuctionsStoryRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  HarvestsIdRoute: HarvestsIdRouteWithChildren,
  AuctionsIndexRoute: AuctionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
