/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as InspectorIndexRouteImport } from './routes/inspector/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as InspectorValidateRouteImport } from './routes/inspector/validate'
import { Route as InspectorProxyRouteImport } from './routes/inspector/proxy'
import { Route as InspectorPlanningRouteImport } from './routes/inspector/planning'
import { Route as InspectorMyCenterRouteImport } from './routes/inspector/my-center'
import { Route as InspectorDashboardRouteImport } from './routes/inspector/dashboard'
import { Route as InspectorAccountsRouteImport } from './routes/inspector/accounts'
import { Route as HarvestsIdRouteImport } from './routes/harvests/$id'
import { Route as FarmerWelcomeRouteImport } from './routes/farmer/welcome'
import { Route as FarmerStockRouteImport } from './routes/farmer/stock'
import { Route as FarmerProfileRouteImport } from './routes/farmer/profile'
import { Route as FarmerOrdersRouteImport } from './routes/farmer/orders'
import { Route as FarmerOnboardingRouteImport } from './routes/farmer/onboarding'
import { Route as FarmerDashboardRouteImport } from './routes/farmer/dashboard'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer/analytics'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth/unauthorized'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuctionsStoryRouteImport } from './routes/auctions/story'
import { Route as AuctionsIdRouteImport } from './routes/auctions/$id'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminLogisticsRouteImport } from './routes/admin/logistics'
import { Route as AdminInspectionsRouteImport } from './routes/admin/inspections'
import { Route as AdminInspectionCentersRouteImport } from './routes/admin/inspection-centers'
import { Route as AdminHarvestsRouteImport } from './routes/admin/harvests'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuctionsRouteImport } from './routes/admin/auctions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as FarmerAuctionsIndexRouteImport } from './routes/farmer/auctions/index'
import { Route as DriverRunsIndexRouteImport } from './routes/driver/runs/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as OrdersIdTrackingRouteImport } from './routes/orders/$id/tracking'
import { Route as InspectorReportsIdRouteImport } from './routes/inspector/reports/$id'
import { Route as HarvestsIdQualityRouteImport } from './routes/harvests/$id/quality'
import { Route as FarmerProductsIdRouteImport } from './routes/farmer/products/$id'
import { Route as FarmerHarvestsNewRouteImport } from './routes/farmer/harvests/new'
import { Route as FarmerHarvestsAnalyzeRouteImport } from './routes/farmer/harvests/analyze'
import { Route as FarmerAuctionsNewRouteImport } from './routes/farmer/auctions/new'
import { Route as FarmerAuctionsBidsRouteImport } from './routes/farmer/auctions/bids'
import { Route as DriverRunsIdRouteImport } from './routes/driver/runs/$id'
import { Route as AuctionsIdAutoBidRouteImport } from './routes/auctions/$id/auto-bid'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as FarmerAuctionsIdBiddersRouteImport } from './routes/farmer/auctions/$id.bidders'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const InspectorIndexRoute = InspectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectorRoute,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const InspectorValidateRoute = InspectorValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorProxyRoute = InspectorProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorPlanningRoute = InspectorPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorMyCenterRoute = InspectorMyCenterRouteImport.update({
  id: '/my-center',
  path: '/my-center',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorDashboardRoute = InspectorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InspectorRoute,
} as any)
const InspectorAccountsRoute = InspectorAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => InspectorRoute,
} as any)
const HarvestsIdRoute = HarvestsIdRouteImport.update({
  id: '/harvests/$id',
  path: '/harvests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerWelcomeRoute = FarmerWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerStockRoute = FarmerStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersRoute = FarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOnboardingRoute = FarmerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsStoryRoute = AuctionsStoryRouteImport.update({
  id: '/auctions/story',
  path: '/auctions/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInspectionCentersRoute = AdminInspectionCentersRouteImport.update({
  id: '/inspection-centers',
  path: '/inspection-centers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHarvestsRoute = AdminHarvestsRouteImport.update({
  id: '/harvests',
  path: '/harvests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerAuctionsIndexRoute = FarmerAuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => FarmerRoute,
} as any)
const DriverRunsIndexRoute = DriverRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIdTrackingRoute = OrdersIdTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => OrdersIdRoute,
} as any)
const InspectorReportsIdRoute = InspectorReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => InspectorRoute,
} as any)
const HarvestsIdQualityRoute = HarvestsIdQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => HarvestsIdRoute,
} as any)
const FarmerProductsIdRoute = FarmerProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHarvestsNewRoute = FarmerHarvestsNewRouteImport.update({
  id: '/harvests/new',
  path: '/harvests/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHarvestsAnalyzeRoute = FarmerHarvestsAnalyzeRouteImport.update({
  id: '/harvests/analyze',
  path: '/harvests/analyze',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAuctionsNewRoute = FarmerAuctionsNewRouteImport.update({
  id: '/auctions/new',
  path: '/auctions/new',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAuctionsBidsRoute = FarmerAuctionsBidsRouteImport.update({
  id: '/auctions/bids',
  path: '/auctions/bids',
  getParentRoute: () => FarmerRoute,
} as any)
const DriverRunsIdRoute = DriverRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => DriverRoute,
} as any)
const AuctionsIdAutoBidRoute = AuctionsIdAutoBidRouteImport.update({
  id: '/auto-bid',
  path: '/auto-bid',
  getParentRoute: () => AuctionsIdRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRoute,
} as any)
const FarmerAuctionsIdBiddersRoute = FarmerAuctionsIdBiddersRouteImport.update({
  id: '/auctions/$id/bidders',
  path: '/auctions/$id/bidders',
  getParentRoute: () => FarmerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/harvests': typeof AdminHarvestsRoute
  '/admin/inspection-centers': typeof AdminInspectionCentersRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auctions/$id': typeof AuctionsIdRouteWithChildren
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/driver/profile': typeof DriverProfileRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/inspector/accounts': typeof InspectorAccountsRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/my-center': typeof InspectorMyCenterRoute
  '/inspector/planning': typeof InspectorPlanningRoute
  '/inspector/proxy': typeof InspectorProxyRoute
  '/inspector/validate': typeof InspectorValidateRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/auctions/$id/auto-bid': typeof AuctionsIdAutoBidRoute
  '/driver/runs/$id': typeof DriverRunsIdRoute
  '/farmer/auctions/bids': typeof FarmerAuctionsBidsRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/driver/runs/': typeof DriverRunsIndexRoute
  '/farmer/auctions/': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/harvests': typeof AdminHarvestsRoute
  '/admin/inspection-centers': typeof AdminInspectionCentersRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auctions/$id': typeof AuctionsIdRouteWithChildren
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/driver/profile': typeof DriverProfileRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/inspector/accounts': typeof InspectorAccountsRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/my-center': typeof InspectorMyCenterRoute
  '/inspector/planning': typeof InspectorPlanningRoute
  '/inspector/proxy': typeof InspectorProxyRoute
  '/inspector/validate': typeof InspectorValidateRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions': typeof AuctionsIndexRoute
  '/inspector': typeof InspectorIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/auctions/$id/auto-bid': typeof AuctionsIdAutoBidRoute
  '/driver/runs/$id': typeof DriverRunsIdRoute
  '/farmer/auctions/bids': typeof FarmerAuctionsBidsRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/driver/runs': typeof DriverRunsIndexRoute
  '/farmer/auctions': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/inspector': typeof InspectorRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/harvests': typeof AdminHarvestsRoute
  '/admin/inspection-centers': typeof AdminInspectionCentersRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/auctions/$id': typeof AuctionsIdRouteWithChildren
  '/auctions/story': typeof AuctionsStoryRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/driver/profile': typeof DriverProfileRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/onboarding': typeof FarmerOnboardingRoute
  '/farmer/orders': typeof FarmerOrdersRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/stock': typeof FarmerStockRoute
  '/farmer/welcome': typeof FarmerWelcomeRoute
  '/harvests/$id': typeof HarvestsIdRouteWithChildren
  '/inspector/accounts': typeof InspectorAccountsRoute
  '/inspector/dashboard': typeof InspectorDashboardRoute
  '/inspector/my-center': typeof InspectorMyCenterRoute
  '/inspector/planning': typeof InspectorPlanningRoute
  '/inspector/proxy': typeof InspectorProxyRoute
  '/inspector/validate': typeof InspectorValidateRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/auctions/': typeof AuctionsIndexRoute
  '/inspector/': typeof InspectorIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/auctions/$id/auto-bid': typeof AuctionsIdAutoBidRoute
  '/driver/runs/$id': typeof DriverRunsIdRoute
  '/farmer/auctions/bids': typeof FarmerAuctionsBidsRoute
  '/farmer/auctions/new': typeof FarmerAuctionsNewRoute
  '/farmer/harvests/analyze': typeof FarmerHarvestsAnalyzeRoute
  '/farmer/harvests/new': typeof FarmerHarvestsNewRoute
  '/farmer/products/$id': typeof FarmerProductsIdRoute
  '/harvests/$id/quality': typeof HarvestsIdQualityRoute
  '/inspector/reports/$id': typeof InspectorReportsIdRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/driver/runs/': typeof DriverRunsIndexRoute
  '/farmer/auctions/': typeof FarmerAuctionsIndexRoute
  '/farmer/auctions/$id/bidders': typeof FarmerAuctionsIdBiddersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/driver'
    | '/farmer'
    | '/inspector'
    | '/marketplace'
    | '/notifications'
    | '/orders'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/harvests'
    | '/admin/inspection-centers'
    | '/admin/inspections'
    | '/admin/logistics'
    | '/admin/roles'
    | '/admin/transactions'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/unauthorized'
    | '/driver/profile'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/inspector/accounts'
    | '/inspector/dashboard'
    | '/inspector/my-center'
    | '/inspector/planning'
    | '/inspector/proxy'
    | '/inspector/validate'
    | '/orders/$id'
    | '/auctions/'
    | '/inspector/'
    | '/orders/'
    | '/admin/users/new'
    | '/auctions/$id/auto-bid'
    | '/driver/runs/$id'
    | '/farmer/auctions/bids'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/inspector/reports/$id'
    | '/orders/$id/tracking'
    | '/admin/users/'
    | '/driver/runs/'
    | '/farmer/auctions/'
    | '/farmer/auctions/$id/bidders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/driver'
    | '/farmer'
    | '/marketplace'
    | '/notifications'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/harvests'
    | '/admin/inspection-centers'
    | '/admin/inspections'
    | '/admin/logistics'
    | '/admin/roles'
    | '/admin/transactions'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/unauthorized'
    | '/driver/profile'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/inspector/accounts'
    | '/inspector/dashboard'
    | '/inspector/my-center'
    | '/inspector/planning'
    | '/inspector/proxy'
    | '/inspector/validate'
    | '/orders/$id'
    | '/auctions'
    | '/inspector'
    | '/orders'
    | '/admin/users/new'
    | '/auctions/$id/auto-bid'
    | '/driver/runs/$id'
    | '/farmer/auctions/bids'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/inspector/reports/$id'
    | '/orders/$id/tracking'
    | '/admin/users'
    | '/driver/runs'
    | '/farmer/auctions'
    | '/farmer/auctions/$id/bidders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/driver'
    | '/farmer'
    | '/inspector'
    | '/marketplace'
    | '/notifications'
    | '/orders'
    | '/admin/analytics'
    | '/admin/auctions'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/harvests'
    | '/admin/inspection-centers'
    | '/admin/inspections'
    | '/admin/logistics'
    | '/admin/roles'
    | '/admin/transactions'
    | '/auctions/$id'
    | '/auctions/story'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/unauthorized'
    | '/driver/profile'
    | '/farmer/analytics'
    | '/farmer/dashboard'
    | '/farmer/onboarding'
    | '/farmer/orders'
    | '/farmer/profile'
    | '/farmer/stock'
    | '/farmer/welcome'
    | '/harvests/$id'
    | '/inspector/accounts'
    | '/inspector/dashboard'
    | '/inspector/my-center'
    | '/inspector/planning'
    | '/inspector/proxy'
    | '/inspector/validate'
    | '/orders/$id'
    | '/auctions/'
    | '/inspector/'
    | '/orders/'
    | '/admin/users/new'
    | '/auctions/$id/auto-bid'
    | '/driver/runs/$id'
    | '/farmer/auctions/bids'
    | '/farmer/auctions/new'
    | '/farmer/harvests/analyze'
    | '/farmer/harvests/new'
    | '/farmer/products/$id'
    | '/harvests/$id/quality'
    | '/inspector/reports/$id'
    | '/orders/$id/tracking'
    | '/admin/users/'
    | '/driver/runs/'
    | '/farmer/auctions/'
    | '/farmer/auctions/$id/bidders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DriverRoute: typeof DriverRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  InspectorRoute: typeof InspectorRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  AuctionsIdRoute: typeof AuctionsIdRouteWithChildren
  AuctionsStoryRoute: typeof AuctionsStoryRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  HarvestsIdRoute: typeof HarvestsIdRouteWithChildren
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/inspector/': {
      id: '/inspector/'
      path: '/'
      fullPath: '/inspector/'
      preLoaderRoute: typeof InspectorIndexRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/inspector/validate': {
      id: '/inspector/validate'
      path: '/validate'
      fullPath: '/inspector/validate'
      preLoaderRoute: typeof InspectorValidateRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/proxy': {
      id: '/inspector/proxy'
      path: '/proxy'
      fullPath: '/inspector/proxy'
      preLoaderRoute: typeof InspectorProxyRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/planning': {
      id: '/inspector/planning'
      path: '/planning'
      fullPath: '/inspector/planning'
      preLoaderRoute: typeof InspectorPlanningRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/my-center': {
      id: '/inspector/my-center'
      path: '/my-center'
      fullPath: '/inspector/my-center'
      preLoaderRoute: typeof InspectorMyCenterRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/dashboard': {
      id: '/inspector/dashboard'
      path: '/dashboard'
      fullPath: '/inspector/dashboard'
      preLoaderRoute: typeof InspectorDashboardRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/inspector/accounts': {
      id: '/inspector/accounts'
      path: '/accounts'
      fullPath: '/inspector/accounts'
      preLoaderRoute: typeof InspectorAccountsRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/harvests/$id': {
      id: '/harvests/$id'
      path: '/harvests/$id'
      fullPath: '/harvests/$id'
      preLoaderRoute: typeof HarvestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/welcome': {
      id: '/farmer/welcome'
      path: '/welcome'
      fullPath: '/farmer/welcome'
      preLoaderRoute: typeof FarmerWelcomeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/stock': {
      id: '/farmer/stock'
      path: '/stock'
      fullPath: '/farmer/stock'
      preLoaderRoute: typeof FarmerStockRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders': {
      id: '/farmer/orders'
      path: '/orders'
      fullPath: '/farmer/orders'
      preLoaderRoute: typeof FarmerOrdersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/onboarding': {
      id: '/farmer/onboarding'
      path: '/onboarding'
      fullPath: '/farmer/onboarding'
      preLoaderRoute: typeof FarmerOnboardingRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/story': {
      id: '/auctions/story'
      path: '/auctions/story'
      fullPath: '/auctions/story'
      preLoaderRoute: typeof AuctionsStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inspection-centers': {
      id: '/admin/inspection-centers'
      path: '/inspection-centers'
      fullPath: '/admin/inspection-centers'
      preLoaderRoute: typeof AdminInspectionCentersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/harvests': {
      id: '/admin/harvests'
      path: '/harvests'
      fullPath: '/admin/harvests'
      preLoaderRoute: typeof AdminHarvestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/auctions/': {
      id: '/farmer/auctions/'
      path: '/auctions'
      fullPath: '/farmer/auctions/'
      preLoaderRoute: typeof FarmerAuctionsIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/driver/runs/': {
      id: '/driver/runs/'
      path: '/runs'
      fullPath: '/driver/runs/'
      preLoaderRoute: typeof DriverRunsIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$id/tracking': {
      id: '/orders/$id/tracking'
      path: '/tracking'
      fullPath: '/orders/$id/tracking'
      preLoaderRoute: typeof OrdersIdTrackingRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/inspector/reports/$id': {
      id: '/inspector/reports/$id'
      path: '/reports/$id'
      fullPath: '/inspector/reports/$id'
      preLoaderRoute: typeof InspectorReportsIdRouteImport
      parentRoute: typeof InspectorRoute
    }
    '/harvests/$id/quality': {
      id: '/harvests/$id/quality'
      path: '/quality'
      fullPath: '/harvests/$id/quality'
      preLoaderRoute: typeof HarvestsIdQualityRouteImport
      parentRoute: typeof HarvestsIdRoute
    }
    '/farmer/products/$id': {
      id: '/farmer/products/$id'
      path: '/products/$id'
      fullPath: '/farmer/products/$id'
      preLoaderRoute: typeof FarmerProductsIdRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/harvests/new': {
      id: '/farmer/harvests/new'
      path: '/harvests/new'
      fullPath: '/farmer/harvests/new'
      preLoaderRoute: typeof FarmerHarvestsNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/harvests/analyze': {
      id: '/farmer/harvests/analyze'
      path: '/harvests/analyze'
      fullPath: '/farmer/harvests/analyze'
      preLoaderRoute: typeof FarmerHarvestsAnalyzeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/auctions/new': {
      id: '/farmer/auctions/new'
      path: '/auctions/new'
      fullPath: '/farmer/auctions/new'
      preLoaderRoute: typeof FarmerAuctionsNewRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/auctions/bids': {
      id: '/farmer/auctions/bids'
      path: '/auctions/bids'
      fullPath: '/farmer/auctions/bids'
      preLoaderRoute: typeof FarmerAuctionsBidsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/driver/runs/$id': {
      id: '/driver/runs/$id'
      path: '/runs/$id'
      fullPath: '/driver/runs/$id'
      preLoaderRoute: typeof DriverRunsIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/auctions/$id/auto-bid': {
      id: '/auctions/$id/auto-bid'
      path: '/auto-bid'
      fullPath: '/auctions/$id/auto-bid'
      preLoaderRoute: typeof AuctionsIdAutoBidRouteImport
      parentRoute: typeof AuctionsIdRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farmer/auctions/$id/bidders': {
      id: '/farmer/auctions/$id/bidders'
      path: '/auctions/$id/bidders'
      fullPath: '/farmer/auctions/$id/bidders'
      preLoaderRoute: typeof FarmerAuctionsIdBiddersRouteImport
      parentRoute: typeof FarmerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminHarvestsRoute: typeof AdminHarvestsRoute
  AdminInspectionCentersRoute: typeof AdminInspectionCentersRoute
  AdminInspectionsRoute: typeof AdminInspectionsRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminHarvestsRoute: AdminHarvestsRoute,
  AdminInspectionCentersRoute: AdminInspectionCentersRoute,
  AdminInspectionsRoute: AdminInspectionsRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverProfileRoute: typeof DriverProfileRoute
  DriverRunsIdRoute: typeof DriverRunsIdRoute
  DriverRunsIndexRoute: typeof DriverRunsIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverProfileRoute: DriverProfileRoute,
  DriverRunsIdRoute: DriverRunsIdRoute,
  DriverRunsIndexRoute: DriverRunsIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerOnboardingRoute: typeof FarmerOnboardingRoute
  FarmerOrdersRoute: typeof FarmerOrdersRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerStockRoute: typeof FarmerStockRoute
  FarmerWelcomeRoute: typeof FarmerWelcomeRoute
  FarmerAuctionsBidsRoute: typeof FarmerAuctionsBidsRoute
  FarmerAuctionsNewRoute: typeof FarmerAuctionsNewRoute
  FarmerHarvestsAnalyzeRoute: typeof FarmerHarvestsAnalyzeRoute
  FarmerHarvestsNewRoute: typeof FarmerHarvestsNewRoute
  FarmerProductsIdRoute: typeof FarmerProductsIdRoute
  FarmerAuctionsIndexRoute: typeof FarmerAuctionsIndexRoute
  FarmerAuctionsIdBiddersRoute: typeof FarmerAuctionsIdBiddersRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerOnboardingRoute: FarmerOnboardingRoute,
  FarmerOrdersRoute: FarmerOrdersRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerStockRoute: FarmerStockRoute,
  FarmerWelcomeRoute: FarmerWelcomeRoute,
  FarmerAuctionsBidsRoute: FarmerAuctionsBidsRoute,
  FarmerAuctionsNewRoute: FarmerAuctionsNewRoute,
  FarmerHarvestsAnalyzeRoute: FarmerHarvestsAnalyzeRoute,
  FarmerHarvestsNewRoute: FarmerHarvestsNewRoute,
  FarmerProductsIdRoute: FarmerProductsIdRoute,
  FarmerAuctionsIndexRoute: FarmerAuctionsIndexRoute,
  FarmerAuctionsIdBiddersRoute: FarmerAuctionsIdBiddersRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface InspectorRouteChildren {
  InspectorAccountsRoute: typeof InspectorAccountsRoute
  InspectorDashboardRoute: typeof InspectorDashboardRoute
  InspectorMyCenterRoute: typeof InspectorMyCenterRoute
  InspectorPlanningRoute: typeof InspectorPlanningRoute
  InspectorProxyRoute: typeof InspectorProxyRoute
  InspectorValidateRoute: typeof InspectorValidateRoute
  InspectorIndexRoute: typeof InspectorIndexRoute
  InspectorReportsIdRoute: typeof InspectorReportsIdRoute
}

const InspectorRouteChildren: InspectorRouteChildren = {
  InspectorAccountsRoute: InspectorAccountsRoute,
  InspectorDashboardRoute: InspectorDashboardRoute,
  InspectorMyCenterRoute: InspectorMyCenterRoute,
  InspectorPlanningRoute: InspectorPlanningRoute,
  InspectorProxyRoute: InspectorProxyRoute,
  InspectorValidateRoute: InspectorValidateRoute,
  InspectorIndexRoute: InspectorIndexRoute,
  InspectorReportsIdRoute: InspectorReportsIdRoute,
}

const InspectorRouteWithChildren = InspectorRoute._addFileChildren(
  InspectorRouteChildren,
)

interface OrdersIdRouteChildren {
  OrdersIdTrackingRoute: typeof OrdersIdTrackingRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdTrackingRoute: OrdersIdTrackingRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface AuctionsIdRouteChildren {
  AuctionsIdAutoBidRoute: typeof AuctionsIdAutoBidRoute
}

const AuctionsIdRouteChildren: AuctionsIdRouteChildren = {
  AuctionsIdAutoBidRoute: AuctionsIdAutoBidRoute,
}

const AuctionsIdRouteWithChildren = AuctionsIdRoute._addFileChildren(
  AuctionsIdRouteChildren,
)

interface HarvestsIdRouteChildren {
  HarvestsIdQualityRoute: typeof HarvestsIdQualityRoute
}

const HarvestsIdRouteChildren: HarvestsIdRouteChildren = {
  HarvestsIdQualityRoute: HarvestsIdQualityRoute,
}

const HarvestsIdRouteWithChildren = HarvestsIdRoute._addFileChildren(
  HarvestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DriverRoute: DriverRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  InspectorRoute: InspectorRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  AuctionsIdRoute: AuctionsIdRouteWithChildren,
  AuctionsStoryRoute: AuctionsStoryRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  HarvestsIdRoute: HarvestsIdRouteWithChildren,
  AuctionsIndexRoute: AuctionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
